# Site settings
title: I Need A Title
email: nobody@wisq.net
description: "I need a description too!"
baseurl: ""
url: "http://wisq.github.io"
twitter_username: wisqnet
github_username:  wisq
#facebook_username: NotGonnaHappen

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules"]
