# Site settings
title: Wisq.net
email: nobody@wisq.net
description: "Videogame adventures, high tech musings, and general mayhem."
baseurl: ""
url: "http://wisq.github.io"
twitter_username: wisqnet
github_username:  wisq
#facebook_username: NotGonnaHappen

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules"]
