# Site settings
title: Wisq.net
email: nobody@wisq.net
description: "Gaming adventures, high tech musings, and general mayhem."
baseurl: ""
url: "https://wisq.net"
twitter_username: wisqnet
github_username:  wisq
#facebook_username: NotGonnaHappen

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude:
  - node_modules
  - "s3_website.yml"
gems:
  - jekyll-sitemap

tag_page_layout: tag_page
tag_page_dir: tag
